/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { searchPokemon, getPokemons, getPokemonsData } from '../api/api'
import Card from '../components/Card'
import Navbar from '../components/Navbar'
import Pokedex from '../components/Pokedex'
import PokemonSearchForm from '../components/PokemonSearchForm'
import { PokemonGetDataResponse, PokemonGetResponse, PokemonSearchResponse } from '../interfaces/pokemon'

export default function Home() {
  const [loading, setLoading] = useState(false)
  const [search, setSearch] = useState('')
  const [notFound, setNotFound] = useState(false)
  const [pokemon, setPokemon] = useState<PokemonSearchResponse>()
  const [pokemonsDataList, setPokemonsDataList] = useState<PokemonSearchResponse[]>()

  const onSearchHandler = async () => {

    try {
      const { data: pokemonSearchResponse } = await searchPokemon(search)
      setPokemon(pokemonSearchResponse)
    }
    catch (error) {
      console.log(`Não encontramos esse pokemon!`)
    }
  }

  const getAllPokemons = async () => {
    try {
      setLoading(true)
      const { data: pokemonsGetResponse } = await getPokemons()
      const results = await Promise.all(pokemonsGetResponse.results.map(async (pokemon) => {
        const { data: pokemonData } = await getPokemonsData(pokemon.url)
        return pokemonData
      }))
      setPokemonsDataList(results)
      setLoading(false)
    }
    catch (error) {
      console.log(`getAllPokemons error: ${error}`)
    }
  }

  useEffect(() => {
    getAllPokemons()
    console.log('carregou')
  }, [])

  return (
    <div>
      <Head>
        <title>Pokédex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar>
        <PokemonSearchForm onChange={e => setSearch(e.target.value.toLowerCase())} onSubmit={onSearchHandler} />
      </Navbar>
      {pokemon &&
        <Card pokemon={pokemon}></Card>
      }
      <Pokedex pokemonsList={pokemonsDataList} loading={loading} />

    </div>
  )
}